import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import db from "../../polybase/config.jsx";
import Link from "next/link";
import { useState, useEffect, use } from "react";
import { useRouter } from "next/router";
import { useAddress } from "@thirdweb-dev/react";

export default function Home() {
  const address = useAddress();
  // Methods

  // getting the url query
  const router = useRouter();
  console.log(router);
  const [notifications, setNotifications] = useState([]);

  useEffect(() => {
    const getNotifications = async () => {
      try {
        const notifications = await db
          .collection("NotificationCollection")
          .where("broker", "==", router.query.id)
          .get();
        console.log(notifications.data);
        setNotifications(notifications.data);
      } catch (error) {
        console.log(error);
      }
    };
    getNotifications();
  }, [router.query.id]);

  // Methods
  const buttonClicked = async () => {
    const id = Math.floor(Math.random() * 1000000000).toString();
    const propertyInfo = await db
      .collection("NotificationCollection")
      .create([id, address, property.broker, property.id]);
    console.log(propertyInfo);
  };

  const exchange = async (id) => {
    const notificationDetails = await db
      .collection("NotificationCollection")
      .where("id", "==", id)
      .get();

    const { data } = notificationDetails.data[0];
    console.log(data);

    try {
      const id = Math.floor(Math.random() * 1000000000).toString();
      const selling = await db
        .collection("SelledPropertiesCollection")
        .create([id, data.buyer, data.broker, data.property_id]);
      console.log(selling);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div>
      <Head>
        <title>HomeChain - Broker Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center h-screen bg-primary p-5">
        <div className="mb-5">
          <h1 className="text-white text-2xl font-extrabold mb-5">
            HomeChain Broker Address - {router.query.id}
          </h1>
        </div>

        <div className="flex flex-col items-center justify-center bg-secondary">
          <h1 className="text-2xl font-extrabold mb-5">Notifications</h1>
          <div className="flex flex-col items-center justify-center border border-black">
            {notifications.map((notification, index) => (
              <div
                key={index}
                className="flex flex-col  bg-gray-100 rounded-lg shadow-lg p-5"
              >
                <h1 className="text-xl font-extrabold mb-5">
                  Notification ID - {notification.data.id}
                </h1>
                <h1 className="text-xl font-extrabold mb-5">
                  Property ID - {notification.data.property_id}
                </h1>
                <h1 className="text-xl font-extrabold mb-5">
                  Buyer Address - {notification.data.buyer}
                </h1>
                <div className="flex flex-row items-center justify-center">
                  <Link href={`/property/${notification.data.property_id}`}>
                    <button className="text-white text-2xl font-extrabold mb-5 border border-black p-2 bg-secondary">
                      View Property
                    </button>
                  </Link>

                  <button
                    onClick={() => exchange(notification.data.id)}
                    className="text-white text-2xl font-extrabold mb-5 border border-black p-2 bg-secondary"
                  >
                    SELL
                  </button>

                  <button className="text-white text-2xl font-extrabold mb-5 border border-black p-2 bg-secondary">
                    Reject
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
