import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import db from "../polybase/config.jsx";
import Link from "next/link";
import { useState } from "react";
import { list } from "postcss";

export default function Home() {
  // Methods
  const [isProfile, setIsProfile] = useState(false);

  const listOfPrperties = [
    {
      id: "1",
      name: "Property 1",
      price: "100000",
      location: "Location 1",
      broker: "Broker 1",
      buyer: "Buyer 1",
      status: "Status 1",
    },
    {
      id: "2",
      name: "Property 2",
      price: "200000",
      location: "Location 2",
      broker: "Broker 2",
      buyer: "Buyer 2",
      status: "Status 2",
    },
  ];

  return (
    <div>
      <Head>
        <title>HomeChain - Broker Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center h-screen bg-primary">
        {isProfile ? (
          <div className="mb-5">
            <h1 className="text-white text-2xl font-extrabold mb-5">
              HomeChain Profile
            </h1>
          </div>
        ) : (
          <div className="mb-5">
            <h1 className="text-white text-2xl font-extrabold mb-5">
              HomeChain Profile Create
            </h1>
          </div>
        )}

        <div className="m-5">
          <Link
            href="/addProperty"
            className="border-4 border-black p-3 bg-white"
          >
            + Add Property
          </Link>
        </div>

        <div className="flex flex-row">
          {listOfPrperties.map((item, index) => (
            <div
              key={index}
              className="h-full mr-10 flex flex-col justify-center items-left"
            >
              <Link
                href={`/property/${item.id}`}
                className="font-extrabold text-5xl border-8 border-black p-5"
              >
                {item.name}
              </Link>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
