import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import db from "../polybase/config.jsx";
import Link from "next/link";

export default function Home() {
  // Methods

  return (
    <div>
      <Head>
        <title>HomeChain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row items-center justify-center h-screen bg-primary p-10">
        <div className="h-full mr-10 flex flex-col justify-center items-left">
          <p className="text-white font-semibold mb-5">Powered By Polybase</p>
          <h1 className="text-white text-2xl font-extrabold mb-5">HomeChain</h1>
          <h3 className="text-white text-5xl  mb-5">
            Easy and secure way of buying/selling houses powered by blockchain
          </h3>
          <Link
            href="/main"
            className="w-fit border-4 border-black p-5 text-white text-bold bg-white  hover:bg-white"
          >
            Get Started
          </Link>
        </div>

        <div>
          <Image
            src="/hero.png"
            className="shadow-lg shadow-black"
            width={800}
            height={800}
          />
        </div>
      </main>
    </div>
  );
}
