import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import db from "../polybase/config.jsx";
import Link from "next/link";

export default function Home() {
  // Methods

  return (
    <div>
      <Head>
        <title>HomeChain - Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center h-screen bg-primary p-10">
        <div className="mb-5">
          <h1 className="text-white text-2xl font-extrabold mb-5">HomeChain</h1>
        </div>
        <div className="flex flex-row">
          <div className="h-full mr-10 flex flex-col justify-center items-left">
            <Link
              href="/broker"
              className="font-extrabold text-5xl border-8 border-black p-5"
            >
              <Image src="/broker.png" width={200} height={200} />
              Broker
            </Link>
          </div>

          <div className="h-full mr-10 flex flex-col justify-center items-left">
            <Link
              href="/buyer"
              className="font-extrabold text-5xl border-8 border-black p-5"
            >
              <Image src="/buyer.png" width={200} height={200} />
              Buyer
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
